### ISSUE TITLE
Issue creating marker file

### ISSUE THREAD

**Issue by nbbarrientos** [lovemun/SEXCMD#3]
Hello,
I was using your pipeline and came across an issue in the 1.extract_chr_from_REF.py script. It runs until line 28 but then in line 29 it gives me the following error:

Traceback (most recent call last):
 File "PATH/SEXCMD/1.extract_chr_from_REF.py", line 29, in <module>
    for idx in xrange(0, len(chr_dict[CHR]), 50):
KeyError: 'chrX'

I was wondering to get some insight into why this might be going on. Thank you very much.

**Comment by lovemun** [comment]
Input fasta file starts the form of ">chr1" and there is a sequence of sex chromosomes. ">chrX" and ">chrY".
Please check your input fasta file.

**Comment by nbbarrientos** [comment]
Thank you very much. I was able to create the marker file and do the sex determination.
